version: '3'
services:
  invidious:
    build:
      context: .
      dockerfile: docker/Dockerfile
    restart: unless-stopped
    ports:
      - "666:3000"
    networks:
      - web
    labels:
      - traefik.http.routers.invidious.rule=Host(`666.pimsnel.com`)
      - traefik.http.routers.invidious.tls=true
      - traefik.http.routers.invidious.tls.certresolver=lets-encrypt
      - traefik.port=666
    environment:
      # Adapted from ./config/config.yml
      INVIDIOUS_CONFIG: |
        channel_threads: 1
        check_tables: true
        feed_threads: 1
        db:
          user: kemal
          password: Lighor5og
          host: postgresql
          port: 5432
          dbname: invidious
        full_refresh: false
        https_only: false
        domain:

networks:
  web:
    external: true
